# Blocker - build with GNU make and any C++17 compiler (g++ >= 9, clang >= 10). No third-party libraries.
CXX      ?= g++
CXXFLAGS ?= -O2 -g
STD      := -std=c++17
WARN     := -Wall -Wextra
HARDEN   := -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE
LDFLAGS  ?=
LDHARDEN := -pie -Wl,-z,relro,-z,now
LIBS     := -pthread

SRC  := src/ui.cpp src/util.cpp src/sha256.cpp src/dns.cpp src/config.cpp src/rules.cpp src/engine.cpp \
        src/lock.cpp src/protect.cpp src/rulesmgr.cpp src/vault.cpp src/popup.cpp src/redirect.cpp src/control.cpp src/daemon.cpp src/main.cpp
HDR  := $(wildcard src/*.hpp) gen/embedded.hpp
UNIT := blocker.service blocker-guard.service blocker-guard.timer src/charset_tables.inc src/core/compat/tables/iana_punycode_tables.inc

.PHONY: all static clean tables-pack tables-show
all: build/blocker

# Unit files and the default rule list are compiled into the binary so the watchdog can restore them.
# The defaults come from a scrambled data table (src/charset_tables.inc), never from a readable file.
gen/embedded.hpp: $(UNIT) Makefile
	@mkdir -p gen
	@{ echo '// generated by make from the files in the project root - do not edit'; \
	   echo '#pragma once'; echo '#include <string>'; echo 'namespace blk::embedded {'; \
	   printf 'inline const char* const SERVICE = R"BLK('; cat blocker.service; printf ')BLK";\n'; \
	   printf 'inline const char* const GUARD_SERVICE = R"BLK('; cat blocker-guard.service; printf ')BLK";\n'; \
	   printf 'inline const char* const GUARD_TIMER = R"BLK('; cat blocker-guard.timer; printf ')BLK";\n'; \
	   printf 'inline const char* const DEFAULT_WHITELIST = R"BLK('; cat src/core/compat/tables/iana_punycode_tables.inc; printf ')BLK";\n'; \
	   echo '// the default block list, scrambled so that `strings` on the binary does not list it'; \
	   echo 'inline const unsigned char DEFAULT_KEYWORDS_ENC[] = {'; \
	   cat src/charset_tables.inc; \
	   echo '0};'; \
	   echo 'inline std::string default_keywords() { std::string s; const size_t n = sizeof(DEFAULT_KEYWORDS_ENC) - 1; s.resize(n); for (size_t i = 0; i < n; ++i) s[i] = static_cast<char>((DEFAULT_KEYWORDS_ENC[i] + 256 - ((i * 7 + 13) % 256)) % 256); return s; }'; \
	   echo '}'; } > $@

build/blocker: $(SRC) $(HDR)
	@mkdir -p build
	$(CXX) $(STD) $(CXXFLAGS) $(WARN) $(HARDEN) $(SRC) -o $@ $(LDFLAGS) $(LDHARDEN) $(LIBS)

# Fully static binary (handy for copying to another machine): make static
static: $(SRC) $(HDR)
	@mkdir -p build
	$(CXX) $(STD) $(CXXFLAGS) $(WARN) $(SRC) -o build/blocker $(LDFLAGS) -static $(LIBS)

clean:
	rm -rf build gen

# Maintenance of src/charset_tables.inc (plain text <-> table). Only needed to change the built-in defaults;
# day-to-day changes are made with `blocker add/allow/remove` after installation.
#   make tables-pack FILE=mylist.txt   scramble a plain list into src/charset_tables.inc
#   make tables-show                   print the table's current content as plain text (to stdout)
tables-pack:
	@test -n "$(FILE)" || { echo "usage: make tables-pack FILE=mylist.txt"; exit 2; }
	@{ echo '// charset_tables.inc - generated lookup data. Do not edit by hand.'; \
	   LC_ALL=C od -An -v -tu1 "$(FILE)" | awk '{ for (i = 1; i <= NF; i++) { printf "%d,", ($$i + (n * 7 + 13)) % 256; n++; if (n % 24 == 0) printf "\n" } } END { printf "\n" }'; } > src/charset_tables.inc
	@echo "src/charset_tables.inc updated - rebuild with 'make'"

tables-show:
	@grep -v '^//' src/charset_tables.inc | tr -d ' \n' | tr ',' '\n' | LC_ALL=C awk 'NF { printf "%c", ($$1 + 256 - ((n * 7 + 13) % 256)) % 256; n++ }'
